#!/usr/bin/env python3
"""
merge_trace.py

Merges freshly-generated GDB trace data (trace_generated.json) into an
existing hand-curated trace.json WITHOUT destroying hand-authored
content. This is the same merge logic used to promote Two Sum's
trace_generated.json into trace.json by hand -- codified here so the
CI pipeline can re-run it safely on every solution.cpp change.

Preserves verbatim:
  - discoveryQuestions
  - predictionQuestions (the question/options/correctOptionIndex/phase
    of every entry -- never rewritten, never dropped)

Replaces wholesale, per phase (bruteForce / optimized):
  - "code", "complexity", "steps" -- taken entirely from
    trace_generated.json, since that's the real GDB-verified data.

predictionQuestions[*].stepIndex remapping (best-effort, conservative):
For each predictionQuestion, this looks at the OLD step (from the
CURRENT trace.json's steps array, at the question's existing
stepIndex) and searches the NEW steps array for a step that shares at
least one variable name with the old step, where every shared
variable name agrees in value. A step qualifies as a candidate only
if none of its shared variables conflict with the old step's values.
Among qualifying candidates, the one with the most shared variables
wins.

If there is no qualifying candidate, or more than one candidate ties
for the most shared variables (an ambiguous match), this is NOT a
clean match: a WARNING is printed and the question's stepIndex is
left UNCHANGED. This script never guesses a new mapping in that case
-- a human needs to review and reword or drop the question.

Usage:
    python3 scripts/merge_trace.py <problem_dir>

Reads:
  <problem_dir>/trace.json            (current, hand-curated)
  <problem_dir>/trace_generated.json  (freshly generated by
                                        parse_gdb_trace.py)
Writes:
  <problem_dir>/trace.json  (merged result, overwritten in place)

Exit code:
  0 -- merge succeeded (even if some questions got WARNINGs and were
       left unchanged -- that's an expected, non-fatal outcome that
       needs human follow-up, not a pipeline failure)
  1 -- required input files missing or malformed
"""

import json
import os
import sys


def load(path):
    with open(path, "r") as f:
        return json.load(f)


def find_matching_step(old_vars, new_steps):
    """Returns the index of the new step that best matches old_vars, or
    None if there's no unambiguous match. A candidate step must not
    conflict with old_vars on any variable name they both have; among
    non-conflicting candidates, the one sharing the most variable
    names wins, and it must win outright (no tie) to count as clean.
    """
    best_idx = None
    best_score = -1
    tie = False

    for idx, step in enumerate(new_steps):
        new_vars = step.get("variables", {})
        common = set(old_vars) & set(new_vars)
        if not common:
            continue
        if any(old_vars[k] != new_vars[k] for k in common):
            continue  # conflicts on a shared variable -> not this step

        score = len(common)
        if score > best_score:
            best_score, best_idx, tie = score, idx, False
        elif score == best_score:
            tie = True

    if best_idx is None or tie:
        return None
    return best_idx


def merge_phase(phase_name, current, generated, prediction_questions, warnings):
    new_section = generated.get(phase_name)
    old_section = current.get(phase_name)

    if new_section is None:
        # Nothing freshly generated for this phase (e.g. a problem with
        # only an "optimized" pipeline) -- leave whatever was already
        # in trace.json for this phase untouched.
        return old_section

    old_steps = (old_section or {}).get("steps", [])

    for i, q in enumerate(prediction_questions):
        if q.get("phase") != phase_name:
            continue

        old_idx = q.get("stepIndex")
        if old_idx is None or old_idx < 0 or old_idx >= len(old_steps):
            warnings.append(
                f"[{phase_name}] predictionQuestion #{i} "
                f"(\"{q.get('question', '')[:60]}...\") has stepIndex "
                f"{old_idx!r}, out of range for the CURRENT {len(old_steps)} "
                f"{phase_name} steps -- leaving stepIndex unchanged."
            )
            continue

        old_vars = old_steps[old_idx].get("variables", {})
        new_idx = find_matching_step(old_vars, new_section["steps"])

        if new_idx is None:
            warnings.append(
                f"[{phase_name}] predictionQuestion #{i} "
                f"(\"{q.get('question', '')[:60]}...\") stepIndex {old_idx} "
                f"has no clean, unambiguous match among the regenerated "
                f"{phase_name} steps -- leaving stepIndex UNCHANGED "
                f"(needs human review: reword or drop this question)."
            )
            continue

        if new_idx != old_idx:
            q["stepIndex"] = new_idx

    return {
        "code": new_section["code"],
        "complexity": new_section["complexity"],
        "steps": new_section["steps"],
    }


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <problem_dir>", file=sys.stderr)
        sys.exit(1)

    problem_dir = sys.argv[1].rstrip("/")
    trace_path = os.path.join(problem_dir, "trace.json")
    gen_path = os.path.join(problem_dir, "trace_generated.json")

    if not os.path.exists(trace_path):
        print(f"Error: {trace_path} not found", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(gen_path):
        print(f"Error: {gen_path} not found -- run parse_gdb_trace.py first", file=sys.stderr)
        sys.exit(1)

    current = load(trace_path)
    generated = load(gen_path)

    prediction_questions = current.get("predictionQuestions", [])
    warnings = []

    merged = dict(current)
    for phase_name in ("bruteForce", "optimized"):
        section = merge_phase(phase_name, current, generated, prediction_questions, warnings)
        if section is not None:
            merged[phase_name] = section

    merged["predictionQuestions"] = prediction_questions
    merged["discoveryQuestions"] = current.get("discoveryQuestions", [])

    with open(trace_path, "w") as f:
        json.dump(merged, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Merged trace written to {trace_path}")

    if warnings:
        print("")
        print("WARNING: some predictionQuestions could not be cleanly remapped:")
        for w in warnings:
            print(f"  - {w}")
    else:
        print("All predictionQuestions remapped cleanly (or none needed remapping).")


if __name__ == "__main__":
    main()
