name: Trace POC
on: [push]
jobs:
  check-gdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install GDB
        run: sudo apt-get update && sudo apt-get install -y gdb
      - name: Compile Solution
        run: |
          cd problems/hash-map/two-sum
          echo -e "\nint main() { return 0; }" >> solution.cpp
          g++ -g -o twosum solution.cpp
          ls -la twosum
